#!/bin/bash

# Remove modules (virtual environment folder)
rm -R modules 2> /dev/null
# Initialize modules folder as a "virtual environment"
virtualenv -p python3 modules
# Activate virtual environment
source modules/bin/activate
# Install all requirements within requirements.txt file
python3 -m pip install -r ./requirements.txt
# Deactivate virtual environment
deactivate
